// generated by react-router-hono-server/dev
import "dotenv/config";
import "dotenv-expand/config"; // Fuck you vite
import { createHonoServer } from "react-router-hono-server/node";

export default await createHonoServer();
